// ---------------------------------------------------------------------------
// IIMK Shuttle — canonical schedule data (single source of truth for the API).
// Format: [ "HH:MM" (24h), [ ...stops in travel order ], "optional note" ]
//
// NOTE: index.html keeps its own copy of this data so the static page works
// with zero network calls. If you edit timings, update BOTH places.
// ---------------------------------------------------------------------------

export const STUDENT = [
  ["08:55", ["C&D Housing", "Phase V Campus", "PGP Auditorium"]],
  ["09:05", ["PGP Auditorium", "Phase V Campus", "C&D Housing"]],
  ["10:25", ["C&D Housing", "Phase V Campus", "PGP Auditorium"]],
  ["10:35", ["PGP Auditorium", "Phase V Campus", "C&D Housing"]],
  ["10:37", ["C&D Housing", "Phase V Campus", "PGP Auditorium"]],
  ["11:00", ["PGP Auditorium", "Phase V Campus", "C&D Housing", "Main Gate"]],
  ["11:45", ["Main Gate", "C&D Housing", "Phase V Campus", "PGP Auditorium"]],
  ["12:05", ["PGP Auditorium", "Phase V Campus", "C&D Housing"]],
  ["12:07", ["C&D Housing", "Phase V Campus", "PGP Auditorium"]],
  ["13:35", ["PGP Auditorium", "Phase V Campus", "C&D Housing"]],
  ["13:38", ["C&D Housing", "Phase V Campus", "PGP Auditorium"]],
  ["13:45", ["PGP Auditorium", "Phase V Campus", "C&D Housing", "Main Gate"]],
  ["14:05", ["Main Gate", "C&D Housing", "Phase V Campus", "PGP Auditorium"]],
  ["14:15", ["PGP Auditorium", "Phase V Campus", "C&D Housing"]],
  ["14:17", ["C&D Housing", "Phase V Campus", "PGP Auditorium"]],
  ["15:00", ["PGP Auditorium", "Phase V Campus", "C&D Housing", "Main Gate"]],
  ["15:30", ["Main Gate", "C&D Housing", "Phase V Campus", "PGP Auditorium"]],
  ["15:50", ["PGP Auditorium", "Phase V Campus", "C&D Housing"]],
  ["15:52", ["C&D Housing", "Phase V Campus", "PGP Auditorium"]],
  ["16:15", ["PGP Auditorium", "Phase V Campus", "C&D Housing", "Main Gate"]],
  ["17:00", ["Main Gate", "C&D Housing", "Phase V Campus", "PGP Auditorium"]],
  ["17:20", ["PGP Auditorium", "Phase V Campus", "C&D Housing"]],
  ["17:22", ["C&D Housing", "Phase V Campus", "PGP Auditorium"]],
  ["18:00", ["PGP Auditorium", "Phase V Campus", "C&D Housing", "Main Gate"]],
  ["18:20", ["Main Gate", "C&D Housing", "Phase V Campus", "PGP Auditorium"]],
  ["18:50", ["PGP Auditorium", "Phase V Campus", "C&D Housing"]],
  ["18:52", ["C&D Housing", "Phase V Campus", "PGP Auditorium"]],
  ["19:00", ["PGP Auditorium", "Phase V Campus", "C&D Housing", "Main Gate"]],
  ["20:00", ["Main Gate", "C&D Housing", "Phase V Campus", "PGP Auditorium"]],
  ["20:10", ["PGP Auditorium", "Phase V Campus", "C&D Housing"]],
  ["20:15", ["C&D Housing", "Phase V Campus", "PGP Auditorium"]],
  ["20:25", ["PGP Auditorium", "Phase V Campus", "C&D Housing", "Main Gate"]],
  ["21:00", ["Main Gate", "C&D Housing", "Phase V Campus", "PGP Auditorium"]],
  ["21:30", ["PGP Auditorium", "Phase V Campus", "C&D Housing", "PGP Auditorium"], "Returns to PGP"],
  ["21:50", ["PGP Auditorium", "Phase V Campus", "C&D Housing", "Main Gate"]],
  ["22:20", ["Main Gate", "C&D Housing", "Phase V Campus", "PGP Auditorium"]],
  ["22:40", ["PGP Auditorium", "Phase V Campus", "C&D Housing", "Main Gate"]],
  ["23:00", ["Main Gate", "C&D Housing", "Phase V Campus", "PGP Auditorium"]],
  ["23:20", ["PGP Auditorium", "Phase V Campus", "C&D Housing", "PGP Auditorium"], "Returns to PGP"],
  ["23:40", ["PGP Auditorium", "Phase V Campus", "C&D Housing", "Main Gate"]],
  ["00:00", ["Main Gate", "C&D Housing", "Phase V Campus", "PGP Auditorium"]],
];

export const STAFF = [
  ["07:45", ["Main Gate", "Main Office"], "Direct"],
  ["08:00", ["Main Office", "Phase V Apt", "Resi Hill", "Main Gate"]],
  ["08:30", ["Main Gate", "Main Office"], "Direct"],
  ["08:42", ["Main Office", "Phase V Apt", "Resi Hill", "Main Office"], "Resi Hill & back"],
  ["10:15", ["Main Office", "Phase V Apt", "Apt-1", "Resi Hill", "Main Office"], "& back"],
  ["10:40", ["Main Office", "Main Gate"]],
  ["11:50", ["Main Gate", "Main Office"]],
  ["13:05", ["Main Office", "Phase V Apt", "Resi Hill", "Main Gate"], "Via Phase-V Apt, R-Hill"],
  ["13:50", ["Main Gate", "Resi Hill", "Phase V Apt", "Main Office"], "Via R-Hill, Phase-V"],
  ["14:30", ["Main Office", "Apt-1", "Resi Hill", "Main Office"], "& back"],
  ["15:30", ["Main Office", "Phase V Apt", "Resi Hill", "Main Gate"], "Via Phase-V Apt, R-Hill"],
  ["16:15", ["Main Gate", "Resi Hill", "Phase V Apt", "Main Office"], "Via R-Hill, Phase-V Apt"],
  ["16:45", ["Main Office", "Main Gate"], "Direct"],
  ["17:15", ["Main Gate", "Main Office"]],
  ["17:40", ["Main Office", "Phase V Apt", "Resi Hill", "Main Gate"], "Via Phase-V Apt, R-Hill"],
  ["18:00", ["Main Gate", "Main Office"]],
  ["18:30", ["Main Office", "Resi Hill", "Phase V Apt", "Main Gate"], "Via R-Hill, Phase-V Apt"],
  ["19:30", ["Main Gate", "Resi Hill", "Phase V Apt", "Main Office"], "Via R-Hill, Phase-V Apt"],
  ["20:30", ["Main Gate", "Phase V Apt", "Resi Hill", "Main Office"], "Via Phase-V, R-Hill"],
  ["21:30", ["Main Office", "Main Gate"]],
  ["21:55", ["Main Office", "Main Gate"]],
];
